org: carlserquina
app: food-cost-app
service: food-cost-api

frameworkVersion: ~4.17.1

params:
  default:
    domain: ${sls:stage}.foodcostapi.com
  prod:
    domain: foodcostapi.com
  dev:
    domain: dev.foodcostapi.com

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-southeast-2
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: food-cost-deployment-bucket-795796019955
    blockPublicAccess: true
  environment:
    DB_USER: ${env:DB_USER, 'foodcostadmin'}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: ${env:DB_NAME, 'foodcost'}
    DB_HOST: ${env:DB_HOST}
    NODE_ENV: ${opt:stage, 'production'}
  tags:
    environment: ${sls:stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"
        - Effect: Allow
          Action:
            - rds:*
          Resource: "*"

functions:
  FoodCostLambda:
    handler: lambda.handler
    memorySize: 512
    timeout: 30
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: "*"
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
            allowCredentials: false

plugins:
  - serverless-appsync-plugin

appSync:
  name: FoodCostApi
  authentication:
    type: API_KEY
  schema: ./src/schema.graphql
  useResolverFunctions: true
  dataSources:
    FoodCostLambdaDataSource:
      type: AWS_LAMBDA
      config:
        functionName: FoodCostLambda

package:
  individually: true
  include:
    - lambda.js
    - resolvers.js
    - data-source.js
    - src/schema.graphql
    - node_modules/**
