org: carlserquina
app: food-cost-app
service: food-cost-api

frameworkVersion: ^4

params:
  default:
    domain: ${sls:stage}.foodcostapi.com
  prod:
    domain: foodcostapi.com
  dev:
    domain: dev.foodcostapi.com

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-southeast-2
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: food-cost-deployment-bucket-795796019955
    blockPublicAccess: true
    serverSideEncryption: AES256
  environment:
    DB_USER: ${env:DB_USER, 'foodcostadmin'}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: ${env:DB_NAME, 'foodcost'}
    DB_HOST: ${env:DB_HOST}
    NODE_ENV: ${opt:stage, 'production'}
  tags:
    environment: ${sls:stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
          Resource: "arn:aws:s3:::food-cost-deployment-bucket-795796019955/*"
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"
        - Effect: Allow
          Action:
            - rds:*
          Resource: "*"

functions:
  FoodCostLambda:
    handler: lambda.handler
    memorySize: 512
    timeout: 29 # Set to 29 to match API Gateway
    package:
      individually: true
      patterns:
        - lambda.js
        - resolvers.js
        - resolver.js
        - data-source.js
        - "!node_modules/**"

plugins:
  - serverless-appsync-plugin

appSync:
  name: FoodCostApi
  authentication:
    type: API_KEY
  schema: src/schema.graphql
  dataSources:
    FoodCostLambdaDataSource:
      type: AWS_LAMBDA
      config:
        functionName: FoodCostLambda
  resolvers:
    Query.dashboardStats:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
      code: resolver.js
    Query.ingredients:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
      code: resolver.js
    Query.recipes:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
      code: resolver.js
    Query.sales:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
      code: resolver.js
    Mutation.addIngredient:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
      code: resolver.js
    Mutation.createRecipe:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
      code: resolver.js
    Mutation.recordSale:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
      code: resolver.js

package:
  individually: true
  patterns:
    - src/schema.graphql
    - "!**" # Exclude all other files not explicitly included
