org: carlserquina
app: food-cost-app
service: food-cost-api

frameworkVersion: ~4.17.1

params:
  default:
    domain: ${sls:stage}.foodcostapi.com
  prod:
    domain: foodcostapi.com
  dev:
    domain: dev.foodcostapi.com

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-southeast-2
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: food-cost-deployment-bucket-795796019955
    blockPublicAccess: true
  environment:
    DB_USER: ${env:DB_USER, 'foodcostadmin'}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: ${env:DB_NAME, 'foodcost'}
    DB_HOST: ${env:DB_HOST}
    NODE_ENV: ${opt:stage, 'production'}
  tags:
    environment: ${sls:stage}

functions:
  FoodCostLambda:
    handler: lambda.handler
    memorySize: 512
    timeout: 30
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
          timeout: 30

plugins:
  - serverless-appsync-plugin

appSync:
  name: FoodCostApi
  authentication:
    type: API_KEY
  schema: ./src/schema.graphql
  dataSources:
    FoodCostLambdaDataSource:
      type: AWS_LAMBDA
      config:
        functionName: FoodCostLambda
  resolvers:
    Query.dashboardStats:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
    Query.ingredients:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
    Query.recipes:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
    Query.sales:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
    Mutation.addIngredient:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
    Mutation.createRecipe:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
    Mutation.recordSale:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
    DashboardStats.totalSales:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
    DashboardStats.totalCosts:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
    DashboardStats.totalMargin:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
    DashboardStats.lowStockIngredients:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
    Ingredient.id:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
    Ingredient.name:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
    Ingredient.unitPrice:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
    Ingredient.unit:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
    Ingredient.stockQuantity:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
    Ingredient.restockThreshold:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
    Recipe.id:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
    Recipe.name:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
    Recipe.totalCost:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
    Recipe.suggestedPrice:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
    Recipe.ingredients:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
    RecipeIngredient.id:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
    RecipeIngredient.quantity:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
    RecipeIngredient.ingredient:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
    Sale.id:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
    Sale.saleAmount:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
    Sale.createdAt:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource
    Sale.recipe:
      kind: UNIT
      dataSource: FoodCostLambdaDataSource

package:
  individually: true
  include:
    - lambda.js
    - resolvers.js
    - data-source.js
    - src/schema.graphql
    - node_modules/**
