org: carlserquina
app: food-cost-app
service: food-cost-api

frameworkVersion: ^4

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-southeast-2
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: food-cost-deployment-bucket-795796019955
    blockPublicAccess: true
    serverSideEncryption: AES256
  environment:
    NODE_ENV: ${opt:stage, 'production'}
  tags:
    environment: ${sls:stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
        - dynamodb:BatchGetItem
        - dynamodb:BatchWriteItem
        - dynamodb:TransactWriteItems
      Resource:
        - arn:aws:dynamodb:ap-southeast-2:*:*:table/Ingredients
        - arn:aws:dynamodb:ap-southeast-2:*:*:table/Recipes
        - arn:aws:dynamodb:ap-southeast-2:*:*:table/Sales
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:DeleteObject
      Resource: "arn:aws:s3:::food-cost-deployment-bucket-795796019955/*"

functions:
  api:
    handler: lambda.handler
    memorySize: 512
    timeout: 29
    package:
      individually: true
      patterns:
        - lambda.js
        - "node_modules/**"
    events:
      # All REST endpoints with CORS enabled
      - http:
          path: ingredients
          method: get
          cors: true
      - http:
          path: ingredients
          method: post
          cors: true
      - http:
          path: ingredients/{id}
          method: delete
          cors: true

      - http:
          path: recipes
          method: get
          cors: true
      - http:
          path: recipes
          method: post
          cors: true
      - http:
          path: recipes/{id}
          method: delete
          cors: true

      - http:
          path: sales
          method: get
          cors: true
      - http:
          path: sales
          method: post
          cors: true
      - http:
          path: sales/{id}
          method: delete
          cors: true

      - http:
          path: dashboard
          method: get
          cors: true

package:
  individually: true
  patterns:
    - lambda.js
    - "node_modules/**"
